# Hugo config
# https://gohugo.io/overview/configuration/

baseurl = "https://davidcalhounphotography.com/blog"
languageCode = "en-US"
title = "David Calhoun - Photography Blog"
theme = "hemingway-dc-mod"
copyright = "&copy; <a href=\"https://davidcalhounphotography.com\">David Calhoun</a> 2017"
disqusShortname = "davidcalhounphotography"
googleAnalytics = "UA-83942647-1"

[permalinks]
post = "/:title/"

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.socialicons]]
url = "https://davidcalhounphotography.com/"
fa_icon = "fa-camera"

[[params.socialicons]]
url = "https://www.youtube.com/channel/UCg5jVvaChTjkL74IQ334FzQ"
fa_icon = "fa-youtube"

[[params.socialicons]]
url = "https://instagram.com/davidcalhounphotography/"
fa_icon = "fa-instagram"

[[params.socialicons]]
url = "/blog/index.xml"
fa_icon = "fa-rss"

[params.social]
facebook		= "davidcalhounphotography"
facebook_admin	= "68600487"
facebook_appid  = "300765353714296"
twitter			= "franksvalli"
twitter_domain	= "davidcalhounphotography.com"
instagram		= "davidcalhounphotography"
youtube			= "UCg5jVvaChTjkL74IQ334FzQ"
linkedin		= "davidcalhoun"


[params.authors.David]
name			= "David Calhoun"
organization    = "David Calhoun Photography"
org_logo        = "http://davidcalhounphotography.com/images/david-calhoun-logo.png"
org_logo_width  = 500
org_logo_height = 500
thumbnail		= "http://themaingate.net/david-calhoun.jpg"
thumbnail_width = "477"
thumbnail_height = "602"
images			= [
					"http://themaingate.net/david-calhoun.jpg"
				]
bio				= "Photographer and web developer based in Big Bear, CA, USA"
email			= "davidcalhounphotography@gmail.com"

[params.authors.David.social]
facebook		= "davidcalhounphotography"
